{% set name = "python-gfal2" %}
{% set version = "1.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.cern.ch/dmc/gfal2-bindings/-/archive/v{{ version }}/gfal2-bindings-v{{ version }}.tar.gz
  sha256: b466d729a20146248c49a560d79e79e135b6c1b1666dae9edb7044ede83cdbf7
  patches:
    # Patches for conda
    - 0001-Disable-Boost_NO_BOOST_CMAKE.diff
    - 0002-Fix-gettext-directory-on-Darwin.patch
    - 0003-Use-statically-linked-Python.patch  # [py3k and osx]
    - 0004-disable-python27.patch

build:
  number: 1
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  ignore_run_exports:
    - glib

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - python
    - pip
    - gfal2
    - boost
    - glib
  run:
    - python
    - {{ pin_compatible('boost', max_pin='x.x.x') }}
    - {{ pin_compatible('glib', max_pin='x.x') }}

test:
  imports:
    - gfal2

about:
  home: Python bindings for gfal 2.0
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: GFAL (Grid File Access Library) is a C library providing an abstraction layer of the grid storage system complexity.
  description: |
    GFAL (Grid File Access Library) is a C library providing an abstraction
    layer of the grid storage system complexity. The version 2 of GFAL tries to
    simplify at the maximum the file operations in a distributed environment.
    The complexity of the grid is hidden from the client side behind a simple
    common POSIX API. GFAL2 is able to manage all the common used file access
    protocols in a grid & cloud environment.
  doc_url: https://dmc-docs.web.cern.ch/dmc-docs/gfal2-python.html
  dev_url: https://gitlab.cern.ch/dmc/gfal2-bindings

extra:
  recipe-maintainers:
    - chrisburr
