{% set name = "python-gfal2" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.cern.ch/dmc/gfal2-bindings/-/archive/v{{ version }}/gfal2-bindings-v{{ version }}.tar.gz
  sha256: 187ef74043726ca1cd96e233689616b691952063ed54653cfece02a974b14c95
  patches:
    - 0001-Disable-Boost_NO_BOOST_CMAKE.patch
    - 0002-Disable-Python-2.7.patch

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  ignore_run_exports:
    - glib

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - python
    - pip
    - gfal2
    - libboost-python-devel
    - glib
  run:
    - python

test:
  imports:
    - gfal2

about:
  home: Python bindings for gfal 2.0
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: GFAL (Grid File Access Library) is a C library providing an abstraction layer of the grid storage system complexity.
  description: |
    GFAL (Grid File Access Library) is a C library providing an abstraction
    layer of the grid storage system complexity. The version 2 of GFAL tries to
    simplify at the maximum the file operations in a distributed environment.
    The complexity of the grid is hidden from the client side behind a simple
    common POSIX API. GFAL2 is able to manage all the common used file access
    protocols in a grid & cloud environment.
  doc_url: https://dmc-docs.web.cern.ch/dmc-docs/gfal2-python.html
  dev_url: https://gitlab.cern.ch/dmc/gfal2-bindings

extra:
  recipe-maintainers:
    - chrisburr
